### ISSUE TITLE
Formtastic dependency should be ~> 2.3, not >= 2.2

### ISSUE THREAD

**Issue by Ahti** [mjbellantoni/formtastic-bootstrap#107]
The current gemspec allows formtastic-bootstrap to be installed with formtastic 3.0.0.

This breaks the `:input` form element (and maybe others), because formtastic dropped `::GroupedCollections`, which is included by `::SelectInput`.

So it would be nice if this was fixed, but in the meantime, setting the dependency to not allow 3.0.0 would be very useful (this issue is kind of hard to find, because rails seems to swallow the underlying exception).

**Comment by sodabrew** [comment]
Resolved by #116
