### ISSUE TITLE
Formtastic removed GroupedCollections included in `select_input.rb` but Formtastic Bootstrap didn't

### ISSUE THREAD

**Issue by siruguri** [mjbellantoni/formtastic-bootstrap#108]
In `lib/formtastic-bootstrap/inputs/select_input.rb`, this line should be deleted

    include Base::GroupedCollections

Due to [this commit](https://github.com/justinfrench/formtastic/commit/01cbc281f422e06e87215cf95abe3fba76c6e2d8#diff-8e1c256d5171773b75ef842467e9eca7) made in Formtastic.

**Comment by sodabrew** [comment]
Resolved by #116
