### ISSUE TITLE
Default hint class

### ISSUE THREAD

**Issue by oneiros** [mjbellantoni/formtastic-bootstrap#11]
A small suggestion:
Currently, formtastic-bootstrap defaults to help-inline as the class for hints.

I have an application with some very long hint texts. Those look terrible with help-inline, so I use help-block instead.

In the form examples at http://twitter.github.com/bootstrap/#forms help-block seems to be the preferred class as well.

So maybe it might make sense to change the default in formtastic-bootstrap to help-block. In any way it would be nice to add instructions to the README how to configure this globally.

**Comment by sodabrew** [comment]
Closing for lack of updates.
