### ISSUE TITLE
Formtastic is changing how to namespace inputs

### ISSUE THREAD

**Issue by mikz** [mjbellantoni/formtastic-bootstrap#113]
Hi,

there is formtastic pull request justinfrench/formtastic#1063 that should be merged before the end of the year (hope).

It changes how formtastic looks up inputs/action classes. I already tried how that would work for activeadmin in mikz/activeadmin@3d933a3 and it worked great.

So please if you have any feedback, write it here or in the justinfrench/formtastic#1063.

**Comment by optimum-dulopin** [comment]
@jkelleyj : it seems to be working quiet well except for select_input , dont know why.

**Comment by sodabrew** [comment]
@jkelleyj Would you be able to provide a PR to adjust this in the gem?

**Comment by mikz** [comment]
The similar change was done in https://github.com/activeadmin/activeadmin/pull/3633
I do not know if formtastic-bootstrap has own form builder or not. But if yes, it should be trivial to use new namespaces.

**Comment by jkelleyj** [comment]
Thanks @optimum-dulopin and @mikz.  @sodabrew I'll give it a shot today with the @mikz approach.

**Comment by jkelleyj** [comment]
@sodabrew I'm getting some basic rspec setup issues w/ formtastic when trying to run tests.  
This line:
https://github.com/mjbellantoni/formtastic-bootstrap/blob/master/spec/spec_helper.rb

That adds the formtastic spec helper is unhappy because:
`<module:FormtasticSpecHelper>': uninitialized constant RSpec::Mocks::Double (NameError)`

Am I missing something obvious with the testing setup?

**Comment by jkelleyj** [comment]
After a bit more fiddling I noted an rspec version difference between formtastic and this repo.  Going to try bumping to 2.14 (from 2.12.2) as part of this PR

**Comment by jkelleyj** [comment]
@sodabrew I saw in the readme that lots of tests aren't passing.  Can you give me a sense of how many were failing before so I can tell if anything broke with my upgrade to 2.14?

**Comment by jkelleyj** [comment]
Resolving these issues in https://github.com/mjbellantoni/formtastic-bootstrap/pull/116

**Comment by sodabrew** [comment]
Merged #116.
