### ISSUE TITLE
Send latest version to Ruby Gems

### ISSUE THREAD

**Issue by b4ugh** [mjbellantoni/formtastic-bootstrap#124]
Double label for boolean (looks like it was merged into Master on Feb 13th 2015) hasn't been pushed to rubygems - can you please push this?  Thanks

**Comment by fredngo** [comment]
+1 here -- new release plz!

**Comment by sodabrew** [comment]
Done! https://rubygems.org/gems/formtastic-bootstrap/versions/3.1.1
