### ISSUE TITLE
Cannot add class to date inputs

### ISSUE THREAD

**Issue by rupert654** [mjbellantoni/formtastic-bootstrap#20]
The following doesn't work:

```ruby
f.input :date_of_birth, input_html: { class: "ui-datepicker" }
```

Other attributes, like `value` can  be placed into the `input_html` hash and are changed just fine. Additionally the `class` attribute can be altered for other inputs with no problems. However, they are ignored for dates. I know that date handling is not fully complete so this might be by design rather than a bug but, in that case, it might be useful to mention that in the README.

Current workaround:

```ruby
f.input :date_of_birth, as: :string, input_html: { class: "ui-datepicker" }
```

**Comment by jtomaszewski** [comment]
This should be okay now.
