### ISSUE TITLE
Problem with date fields

### ISSUE THREAD

**Issue by lchojnowski** [mjbellantoni/formtastic-bootstrap#27]
When I try to add date text field to my formtastic-bootstrap form:

```
= form.input :start_on
```

I get the following error:

```
undefined method `text_field_date' for #<#<Class:0x007f8153f03990>:0x007f8153efd888>
```

**Comment by jtomaszewski** [comment]
If it's still in an issue (propably rails 3.2 only), please provide a fix. Meanwhile, I'm closing it.
