### ISSUE TITLE
semantic_fields_for + :time bug

### ISSUE THREAD

**Issue by jmontoyaa** [mjbellantoni/formtastic-bootstrap#29]
When using f.semantic_fields_for and a :time attribute there is no name attibute in that input.

Example:

	<%= f.semantic_fields_for :schedules do |schedule| %>
        <%= render :partial => 'schedule_fields',  :locals => { :f => schedule} %>	  
	<% end %>

in my partial:

<%= f.input :start ,       :as => :time %>

the result is a input with no name

**Comment by jtomaszewski** [comment]
This should be okay now. Closing it.
