### ISSUE TITLE
Hint-block span inside the prepend div

### ISSUE THREAD

**Issue by danilotorrisi** [mjbellantoni/formtastic-bootstrap#41]
When you use a prepend text the hint-block span has been added inside the prepend div just like this

```
<div class="controls">
 <div class="input-prepend">
  <span class="add-on" ...>
  <input ..>
  <span class="help-block"> ... </span>
 </div>
</div>
```
But from what I understood the hint block should be outside the input prepend otherwise the font-size won't be properly setted.

```
<div class="controls">
 <div class="input-prepend">
  <span class="add-on" ...>
  <input ..>
 </div>
 <span class="help-block"> ... </span>
</span>
```
8a08a48561e8ee2655f502855212da770f908eaa

**Comment by sodabrew** [comment]
Closed for lack of updates.
