### ISSUE TITLE
Inline helps should be inside the controls class

### ISSUE THREAD

**Issue by jarijokinen** [mjbellantoni/formtastic-bootstrap#42]
Based on Twitter Bootstrap documentation, inline errors and other inline help elements should be placed inside the controls class:

    <div class="control-group">
      <label class="control-label" for="foo">Foo</label>
      <div class="controls">
        <input type="text" id="foo">
        <span class="help-inline">Username is taken</span>
      </div>
    </div>

Formtastic-bootstrap puts them outside the controls class, like this:

    <div class="control-group">
      <label class="control-label" for="foo">Foo</label>
      <div class="controls">
        <input type="text" id="foo" />
      </div>
      <span class="help-inline">can't be blank</span>
    </div>

Here's a screenshot what happens when using horizontal forms:

http://i47.tinypic.com/2075ix0.gif

**Comment by jtomaszewski** [comment]
`.controls` div no longer exists in bootstrap 3. Thus, I'm closing the issue.
