### ISSUE TITLE
Version 2.0.0 breaks the Formtastic :wrapper_html param and also the :as => :hidden

### ISSUE THREAD

**Issue by marzapower** [mjbellantoni/formtastic-bootstrap#47]
When creating a new form, and using the :wrapper_html param, the 2.0.0 version of this gem does not work as expected. In fact, the whole param is completely ignored.
This problem is related to this gem, in fact if I remove the initializer call from the stack, the formtastic gem works as expected.
I also noticed that those fields that are marked as hidden are always being shown.

**Comment by sodabrew** [comment]
Closed for lack of updates, presumed to be fixed in formtastic-bootstrap >= 3.0.
