### ISSUE TITLE
Cannot install formtastic-bootstrap

### ISSUE THREAD

**Issue by monterey01** [mjbellantoni/formtastic-bootstrap#54]
I get the below error message when installing formstatic-bootstrap.
Error installing formtastic-bootstrap: formtastic-bootstrap requires formtastic-bootstrap (>= 0). 

Can someone help me solving the issue?

**Comment by jamesmartin** [comment]
If, for your sins, you *must* stick with formtastic-bootstrap < v3x for some reason, then you can use our [fork](https://github.com/SplitIt/formtastic-bootstrap/releases/tag/v2.0.1), which simply removes the self-dependency.
