### ISSUE TITLE
update docs (FormBuilder "buttons" instance method now called "actions")

### ISSUE THREAD

**Issue by nzaillian** [mjbellantoni/formtastic-bootstrap#56]
Formtastic 2.2+ API has replaced the "buttons" FormBuilder instance method with an "actions" method, so the example code in the README is now out-of-date/broken.  I was going to fork and make a pull request but it hardly seems worth it for one-line change to the docs, so this is just a heads up that "f.buttons do \<block\>" is now "f.actions do \<block\>"

**Comment by jtomaszewski** [comment]
Closing, as the whole "Overview" section in README needs to be rewritten anyway.
