### ISSUE TITLE
semantic_fields_for generates old style markup

### ISSUE THREAD

**Issue by meliborn** [mjbellantoni/formtastic-bootstrap#76]
All parent inputs has twitter bootstrap markup, but semantic_fields_for inputs has old style markup with `<li>` and `<ol>`

**Comment by jtomaszewski** [comment]
Please include all the source (f.e. of the `Surveyor::Helpers::FormtasticCustomInput`) so we can investigate. Then we'll reopen the issue.

P.S. In my opinion, there should be no problem with custom inputs inherited from formtastic-bootstrap inputs, as I have a couple of them in my own rails app.
