### ISSUE TITLE
Required attribute not automatically added to input field

### ISSUE THREAD

**Issue by creativetags** [mjbellantoni/formtastic-bootstrap#79]
Formtastic detects when a model has something like validates :name, :presence => true and adds a required attribute to the relevant input field. With your bootstrap modifications it adds a required class to the control-group div but not a required attribute to the input field which means jquery.validate doesn't work. You can make it add the attribute with input_html: { required: true }

**Comment by jtomaszewski** [comment]
@jibiel summed it up pretty well. Closing the issue then.
