### ISSUE TITLE
Date Select defaulting to placeholder .span1, .span2, .span1

### ISSUE THREAD

**Issue by samiur** [mjbellantoni/formtastic-bootstrap#80]
This is happening because of: https://github.com/mjbellantoni/formtastic-bootstrap/blob/master/lib/formtastic-bootstrap/inputs/base/timeish.rb#L49

I'm pretty sure this is unintended behavior, and I think the placeholder should be specifiable, or otherwise default to something more meaningful.

**Comment by jtomaszewski** [comment]
Fix landed in master. placeholders are empty by default, but you can change them with `:fragment_placeholders`.

See those links for more info:
- https://github.com/mjbellantoni/formtastic-bootstrap/blob/2e28e570191fa5e35414208010e0472345c7bc4a/lib/formtastic-bootstrap/inputs/base/timeish.rb#L14-L21
- https://github.com/mjbellantoni/formtastic-bootstrap/blob/2e28e570191fa5e35414208010e0472345c7bc4a/lib/formtastic-bootstrap/inputs/base/timeish.rb#L60-L62
