### ISSUE TITLE
using buttons for actions

### ISSUE THREAD

**Issue by nicholasjstock** [mjbellantoni/formtastic-bootstrap#83]
Per formatsitc-bootstrap readme:
```
<%= semantic_form_for @client do |f| %>
  <%= f.inputs  do %>
		<%=f.input :login %>
		<%=f.input :display_name %>
	<%end%>
 	<%= f.actions do %>
		<%= f.action :submit %>
	<% end %>
<% end %>
```
when I look at this form,  the submit button isn't styled correctly. 
the html is:
```
<fieldset class="form-actions">
    <input class="btn" name="commit" type="submit" value="Update Client">
</fieldset>
```
Per bootstraps documentation: 
"typically you'll want to apply these to only <a> and <button> elements for the best rendering."

shouldn't it be this instead? 
```
<fieldset class="form-actions">
 <button class="btn" name="commit" type="submit" >Update Client</button>
</fieldset>
```
Am I using it wrong?

**Comment by jtomaszewski** [comment]
You can do it via `f.action :submit, as: :button`.
