### ISSUE TITLE
Errr, does this gem do anything?

### ISSUE THREAD

**Issue by JohnSmall** [mjbellantoni/formtastic-bootstrap#92]
I've installed the gem, set the initialiser code, changed application.css, and... Nothing happens. The generated form has exactly the same structure, even down to labels, fieldsets and date select fields which the docs say would be different in formtastic-bootstrap. 
I'm using;-
    rvm ruby 2.0.0-p247
    Rails 4.0.1
    gem 'sass-rails', '~> 4.0.0'
    gem 'bootstrap-sass', '~> 3.0.3.0'
    gem "formtastic", "~> 2.3.0.rc2"
    gem 'formtastic-bootstrap'

in config/initializers/formtastic.rb I have;-
    Formtastic::Helpers::FormHelper.builder = FormtasticBootstrap::FormBuilder

in app/assets/stylesheets/application.css I have;-
     *= require formtastic-bootstrap

What's the secret incantation required to get it working?

**Comment by sodabrew** [comment]
@daveharris I'm sorry I'm not sure what's going on. If you still need help, please open a new issue? I've also just posted formtastic-bootstrap 3.1.0 which may help since Formtastic itself has been updated quite a bit recently.

**Comment by daveharris** [comment]
Thanks @sodabrew. It's probably because I'm using kinda outdated stuff. I will try and update but unfortunately there is a lot of use of deprecated options so I can't just upgrade immediately :(
